version: "2"
services:
  rlrs3:
    build: .
    ports:
      - 9600:9600/tcp 
      - 9600:9600/udp 
      - 8081:8081
    volumes: 
      - ./acServer:/acServer
      - ./conf_rlrs3:/acServer/cfg
      - ./setups:/acServer/setups
      - ./results_s3:/acServer/results

  rlrs4:
    build: .
    ports:
      - 9601:9601/tcp 
      - 9601:9601/udp 
      - 8082:8082
    volumes: 
      - ./acServer:/acServer
      - ./conf_rlrs4:/acServer/cfg
      - ./setups:/acServer/setups
      - ./results_s4:/acServer/results

  # rlrs5:
  #   build: .
  #   ports:
  #     - 9602:9602/tcp 
  #     - 9602:9602/udp 
  #     - 8083:8083
  #   volumes: 
  #     - ./acServer:/acServer
  #     - ./conf_rlrs5:/acServer/cfg
  #     - ./setups:/acServer/setups
  #     - ./results_s5:/acServer/results

    